# Generated by Django 4.1.3 on 2022-12-14 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('slug', models.CharField(blank=True, max_length=255, verbose_name='Slug')),
                ('pub_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date')),
                ('is_pub', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
