# Generated by Django 4.1.3 on 2022-12-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='is_pub',
            field=models.BooleanField(default=False),
        ),
    ]
