# Generated by Django 4.1.3 on 2022-12-14 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_booksmodel_is_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='pub_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
